# Generated by Django 5.2.8 on 2025-11-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('credits', models.IntegerField()),
                ('schedule', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=100)),
                ('requirements', models.TextField()),
                ('description', models.TextField()),
                ('instruction_mode', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
