# Generated by Django 5.2.8 on 2025-11-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseSubject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
