# Generated by Django 5.2.8 on 2025-11-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_course_coursesubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
    ]
