# Generated by Django 5.2.7 on 2025-12-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_course_created_at_remove_course_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['courseSubject', 'courseID']},
        ),
        migrations.AddField(
            model_name='course',
            name='creator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
